export const SIGNUP_FORM_FIELD_KEY = {
  LOGIN:'LOGIN',
  PASSWORD: 'PASSWORD',
}

export const SIGNUP_TITLE_KEY = {
  REGISTRATION: 'REGISTRATION',
  ACCOUNT: 'ACCOUNT',
  LOADING: 'LOADING',
  CREATE_BUTTON_NAME: 'CREATE_BUTTON_NAME',
}