export const THEME_COLOR = {
  PRIMARY: '#fff',
  TEXT_SECONDARY: '#707070',
  BUTTON_BACKGROUND_COLOR: '#9999ff',
  BUTTON_TEXT_COLOR: 'black',
  BUTTON_BORDER_COLOR: 'blue',
  ERROR_MESSAGE_COLOR: 'red',
  INPUT_BACKGROUND_COLOR: '#f3f3f3'
};
